#spring.application.name=accommodation-marketplace

spring:
  application:
    name: accommodation-marketplace
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:mysql://localhost:3306/quickcart
    username: root
    password: "ManuPatel@31"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   #set update for quick dev, use validate + flyway in prod
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false


#App configuration

app:
  jwt:
    secret: ${JWT_SECRET}
