spring:
  application:
    name: Accommodation-Marketplace
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/sys}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:tiger}
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl_auto: update
      properties:
        hibernate:
          format-sql: false